services:
  db:
    container_name: exam_db
    image: postgres:18
    environment:
      POSTGRES_USER: kshrd
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: exam_db
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.5
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'
volumes:
  keycloak_data:
  postgres_data: